import React, { useState } from "react";
import { jsPDF } from "jspdf";
import { 
  Sparkles, 
  Send, 
  Download, 
  ShieldAlert, 
  Brain, 
  Database, 
  CheckCircle2, 
  FileText, 
  HelpCircle 
} from "lucide-react";
import { User, FIR } from "../types";

interface AICopilotProps {
  currentUser: User;
  firs: FIR[];
}

interface CopilotResponse {
  recommendations: string[];
  reasoning: string;
  confidence: number;
  evidence: string[];
}

export function AICopilot({ currentUser, firs }: AICopilotProps) {
  const [query, setQuery] = useState("");
  const [selectedFir, setSelectedFir] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<CopilotResponse | null>(null);

  const suggestedPrompts = [
    {
      label: "Phishing Next Steps",
      text: "Generate tactical next steps for cyber phishing case FIR/0045/2026",
      fir: "FIR/0045/2026"
    },
    {
      label: "Mule Account Trail",
      text: "Analyze transaction trails for potential shell mule accounts linked to Gold Ponzi FIR/0082/2026",
      fir: "FIR/0082/2026"
    },
    {
      label: "Armed Robbery Leads",
      text: "Generate vehicle tracing search patterns for Majestic armed robbery FIR/0112/2026",
      fir: "FIR/0112/2026"
    }
  ];

  const handlePromptSelect = (prompt: typeof suggestedPrompts[0]) => {
    setQuery(prompt.text);
    setSelectedFir(prompt.fir);
  };

  const handleQuerySubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) return;

    setLoading(true);
    setResult(null);

    try {
      const response = await fetch("/api/copilot", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          query,
          firNumber: selectedFir,
          user: currentUser,
          language: "English"
        })
      });
      const data = await response.json();
      setResult(data);
    } catch (err) {
      console.error("Error calling copilot API:", err);
    } finally {
      setLoading(false);
    }
  };

  const handleExportPDF = () => {
    if (!result) return;

    const doc = new jsPDF();
    
    // Official Karnataka State Police Header
    doc.setFillColor(15, 23, 42); // slate-900
    doc.rect(0, 0, 210, 40, "F");
    
    doc.setTextColor(255, 255, 255);
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(16);
    doc.text("KARNATAKA STATE POLICE", 105, 15, { align: "center" });
    
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(10);
    doc.text("CRIME INVESTIGATION DIVISION - TACTICAL CO-PILOT ADVISORY", 105, 22, { align: "center" });
    doc.text("STRICTLY CONFIDENTIAL // LAW ENFORCEMENT SENSITIVE", 105, 28, { align: "center" });

    // Date & Officer Details
    doc.setTextColor(50, 50, 50);
    doc.setFontSize(11);
    doc.setFont("Helvetica", "bold");
    doc.text("REPORT METADATA:", 15, 50);
    doc.setFont("Helvetica", "normal");
    doc.text(`Generated By: ${currentUser.name} (${currentUser.role})`, 15, 56);
    doc.text(`Badge Identifier: ${currentUser.badgeId}`, 15, 62);
    doc.text(`Origin Station: ${currentUser.station}`, 15, 68);
    doc.text(`Timestamp: ${new Date().toLocaleString()}`, 15, 74);
    doc.text(`Reference Subject: ${selectedFir || "General Intelligence inquiry"}`, 15, 80);

    // Divider line
    doc.setDrawColor(200, 200, 200);
    doc.line(15, 85, 195, 85);

    // Query Summary
    doc.setFont("Helvetica", "bold");
    doc.text("TACTICAL INQUIRY:", 15, 93);
    doc.setFont("Helvetica", "italic");
    const splitQuery = doc.splitTextToSize(`"${query}"`, 180);
    doc.text(splitQuery, 15, 99);

    let yOffset = 99 + (splitQuery.length * 6);

    // AI Reasoning Section
    doc.setDrawColor(200, 200, 200);
    doc.line(15, yOffset, 195, yOffset);
    yOffset += 8;

    doc.setFont("Helvetica", "bold");
    doc.text(`EXPLAINABLE AI ADVISORY REASONING (Confidence Level: ${result.confidence}%):`, 15, yOffset);
    doc.setFont("Helvetica", "normal");
    yOffset += 6;
    const splitReasoning = doc.splitTextToSize(result.reasoning, 180);
    doc.text(splitReasoning, 15, yOffset);

    yOffset += (splitReasoning.length * 6) + 6;

    // Recommendations Section
    doc.setFont("Helvetica", "bold");
    doc.text("TACTICAL RECOMMENDATIONS FOR INVESTIGATING OFFICERS:", 15, yOffset);
    doc.setFont("Helvetica", "normal");
    yOffset += 6;

    result.recommendations.forEach((rec, idx) => {
      const splitRec = doc.splitTextToSize(`${idx + 1}. ${rec}`, 175);
      doc.text(splitRec, 15, yOffset);
      yOffset += (splitRec.length * 6) + 2;
    });

    yOffset += 4;
    doc.setFont("Helvetica", "bold");
    doc.text("SUPPORTING EVIDENCE & DATA REFERENCES:", 15, yOffset);
    doc.setFont("Helvetica", "normal");
    yOffset += 6;
    doc.text(result.evidence.join(" | "), 15, yOffset);

    // Official Footer Sign-off
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("This document is generated by an authorized AI node and validated against CCTNS databases.", 105, 285, { align: "center" });

    doc.save(`KSP_Copilot_Briefing_${selectedFir || "General"}.pdf`);
  };

  return (
    <div className="flex flex-col h-full bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden shadow-2xl" id="copilot-panel">
      {/* Header bar */}
      <div className="px-5 py-4 border-b border-slate-800 flex items-center justify-between bg-slate-950/60 backdrop-blur-sm">
        <div className="flex items-center gap-2.5">
          <div className="p-2 bg-blue-500/10 rounded-xl border border-blue-500/20 text-blue-400">
            <Brain className="w-5 h-5 animate-pulse" />
          </div>
          <div>
            <h2 className="text-sm font-bold text-slate-100 flex items-center gap-1.5">
              AI Investigation Copilot
              <span className="px-2 py-0.5 text-[9px] font-black bg-blue-500/20 text-blue-300 rounded border border-blue-500/30 tracking-wider uppercase">
                Tactical Intelligence
              </span>
            </h2>
            <p className="text-[10px] text-slate-400 font-medium">Secured Officer Assistant Node // CCTNS Layer</p>
          </div>
        </div>
        <div className="flex items-center gap-2 text-[10px] bg-slate-900 px-3 py-1.5 rounded-lg border border-slate-800 text-slate-400">
          <span className="w-2 h-2 rounded-full bg-emerald-500 animate-ping"></span>
          Officer Authority: <span className="text-white font-bold">{currentUser.role}</span>
        </div>
      </div>

      <div className="flex-1 grid grid-cols-12 overflow-hidden">
        {/* Left Side: Prompts & Inputs */}
        <div className="col-span-12 lg:col-span-5 p-5 border-r border-slate-800 flex flex-col justify-between overflow-y-auto bg-slate-950/40">
          <div className="space-y-5">
            <div>
              <label className="text-[11px] font-bold uppercase tracking-wider text-slate-400 mb-2.5 block flex items-center gap-1">
                <Sparkles className="w-3.5 h-3.5 text-blue-400" />
                Select Suggested Tactical Focus
              </label>
              <div className="space-y-2">
                {suggestedPrompts.map((p, idx) => (
                  <button
                    key={idx}
                    onClick={() => handlePromptSelect(p)}
                    className="w-full text-left p-3 rounded-xl border border-slate-800 hover:border-slate-700 bg-slate-900/60 hover:bg-slate-900 text-xs transition-all flex flex-col gap-1 text-slate-300 group"
                  >
                    <span className="font-bold text-blue-400 flex items-center justify-between">
                      {p.label}
                      <span className="text-[9px] text-slate-500 group-hover:text-slate-300 transition-colors">Apply &rarr;</span>
                    </span>
                    <span className="text-[11px] text-slate-400 line-clamp-2">{p.text}</span>
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className="text-[11px] font-bold uppercase tracking-wider text-slate-400 mb-2 block">
                Target FIR Context Reference
              </label>
              <select
                value={selectedFir}
                onChange={(e) => setSelectedFir(e.target.value)}
                className="w-full bg-slate-900 border border-slate-800 rounded-xl px-3 py-2 text-xs text-slate-200 focus:border-blue-500 focus:outline-none"
              >
                <option value="">-- Select Active FIR File --</option>
                {firs.map(f => (
                  <option key={f.id} value={f.firNumber}>
                    {f.firNumber} - {f.crimeCategory} ({f.policeStation})
                  </option>
                ))}
              </select>
            </div>
          </div>

          <form onSubmit={handleQuerySubmit} className="mt-5 pt-4 border-t border-slate-800">
            <label className="text-[11px] font-bold uppercase tracking-wider text-slate-400 mb-2 block">
              Inquire Natural Language Instructions
            </label>
            <div className="relative">
              <textarea
                value={query}
                onChange={(e) => setQuery(e.target.value)}
                placeholder="Ask details (e.g., 'What are the main financial risks for FIR/0082/2026?')"
                rows={3}
                className="w-full bg-slate-900 border border-slate-800 rounded-xl pl-3 pr-10 py-2.5 text-xs text-slate-100 placeholder-slate-500 focus:border-blue-500 focus:outline-none resize-none"
              />
              <button
                type="submit"
                disabled={loading}
                className="absolute right-2.5 bottom-3 p-1.5 bg-blue-600 hover:bg-blue-500 disabled:bg-slate-800 text-white rounded-lg transition-colors"
              >
                <Send className="w-3.5 h-3.5" />
              </button>
            </div>
            <p className="text-[9px] text-slate-500 mt-1.5 italic">
              * Inputs are logged, audited, and encrypted in compliance with state surveillance procedures.
            </p>
          </form>
        </div>

        {/* Right Side: Copilot Intelligence Response Area */}
        <div className="col-span-12 lg:col-span-7 p-5 flex flex-col justify-between overflow-y-auto bg-slate-900/40">
          {loading ? (
            <div className="flex-1 flex flex-col items-center justify-center space-y-4 py-12">
              <div className="w-10 h-10 border-4 border-blue-500/30 border-t-blue-500 rounded-full animate-spin"></div>
              <div className="text-center space-y-1">
                <p className="text-xs font-bold text-slate-300">Consulting Neural CCTNS Database Node...</p>
                <p className="text-[10px] text-slate-500">Formulating role-aware tactical directives</p>
              </div>
            </div>
          ) : result ? (
            <div className="space-y-5 flex-1">
              {/* Score & Header info */}
              <div className="flex items-center justify-between p-4 bg-slate-950/60 rounded-xl border border-slate-800">
                <div className="flex items-center gap-3">
                  <div className={`p-2.5 rounded-xl border font-bold text-sm ${
                    result.confidence >= 90 ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20" : 
                    "bg-amber-500/10 text-amber-400 border-amber-500/20"
                  }`}>
                    {result.confidence}%
                  </div>
                  <div>
                    <h3 className="text-xs font-bold text-slate-200">Advisory Confidence Level</h3>
                    <p className="text-[10px] text-slate-500">Based on evidence count and suspect MO match density</p>
                  </div>
                </div>

                <button
                  onClick={handleExportPDF}
                  className="px-3 py-1.5 bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold rounded-lg flex items-center gap-1.5 transition-colors"
                >
                  <Download className="w-3.5 h-3.5" />
                  Export Advisory (PDF)
                </button>
              </div>

              {/* Recommendations */}
              <div className="space-y-2">
                <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider flex items-center gap-1.5">
                  <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                  Tactical Action Directives
                </h3>
                <div className="space-y-2">
                  {result.recommendations.map((rec, index) => (
                    <div key={index} className="p-3 bg-slate-950/25 border border-slate-800 rounded-xl flex gap-3 text-xs leading-relaxed text-slate-300">
                      <span className="font-bold text-blue-400 shrink-0">{index + 1}.</span>
                      <p>{rec}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Explainable AI Reasoning */}
              <div className="p-4 bg-slate-950/50 border border-slate-800 rounded-xl space-y-2">
                <h3 className="text-[11px] font-bold text-blue-400 uppercase tracking-wider flex items-center gap-1.5">
                  <Brain className="w-4 h-4 text-blue-400" />
                  Explainable AI Logic & Core Rationale
                </h3>
                <p className="text-xs text-slate-300 leading-relaxed">{result.reasoning}</p>
              </div>

              {/* Evidence references */}
              <div className="space-y-2">
                <h3 className="text-[10px] font-bold text-slate-400 uppercase tracking-wider flex items-center gap-1.5">
                  <Database className="w-3.5 h-3.5 text-slate-400" />
                  Linked Context Sources
                </h3>
                <div className="flex flex-wrap gap-2">
                  {result.evidence.map((ev, i) => (
                    <span key={i} className="px-2.5 py-1 bg-slate-950 border border-slate-800 rounded text-[10px] font-mono text-slate-400 font-bold">
                      {ev}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center text-center space-y-3 py-12">
              <div className="p-4 bg-slate-950/60 rounded-full border border-slate-800 text-slate-500">
                <ShieldAlert className="w-8 h-8" />
              </div>
              <div className="max-w-[340px] space-y-1">
                <h4 className="text-xs font-bold text-slate-300">Copilot Ready for Inquest</h4>
                <p className="text-[11px] text-slate-500">
                  Select a suggested tactical focus or enter custom investigation goals to command the AI copilot engine.
                </p>
              </div>
            </div>
          )}

          {/* Secure disclaimer */}
          <div className="mt-4 pt-3 border-t border-slate-800/60 flex items-center justify-between text-[9px] text-slate-500">
            <span>🛡️ End-to-end audit ledger encrypted</span>
            <span>Security ID: SEC-KSP-992A</span>
          </div>
        </div>
      </div>
    </div>
  );
}
